= Spring Data BOM

This repository contains the Spring Data BOM (Bill of Materials).

== NES release

- BOM GAV: `cn.bjca.footstone.bpring.data:bjca-footstone-bpring-data-bom:2025.0.13-nes.patch.1` (`pom`)
- Managed NES Data RELEASE modules: Commons / KeyValue / Redis `3.5.13-nes.patch.1`, Elasticsearch `5.5.13-nes.patch.1`
- Nexus: `http://192.168.131.36:8088/repository/releases/`
- Local gates: `./mvnw -pl bom -am -DskipTests install` then consumer import of the BOM
- Exclusions: root aggregator POM and `bom-client` are validation-only and are not published RELEASE artifacts
- Tag: `v2025.0.13-nes.patch.1`

Usage (Maven):

```xml
<dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>cn.bjca.footstone.bpring.data</groupId>
      <artifactId>bjca-footstone-bpring-data-bom</artifactId>
      <version>2025.0.13-nes.patch.1</version>
      <type>pom</type>
      <scope>import</scope>
    </dependency>
  </dependencies>
</dependencyManagement>
```

== Code of Conduct

This project is governed by the link:CODE_OF_CONDUCT.adoc[Spring Code of Conduct]. By participating, you are expected to uphold this code of conduct. Please report unacceptable behavior to spring-code-of-conduct@pivotal.io.

== Maven

Usage in Maven

```xml
<dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>org.springframework.data</groupId>
      <artifactId>spring-data-bom</artifactId>
      <version>${calver.major.minor}</version>
      <type>pom</type>
      <scope>import</scope>
    </dependency>
  </dependencies>
</dependencyManagement>

<dependencies>
  <dependency>
    <groupId>org.springframework.data</groupId>
    <artifactId>spring-data-commons</artifactId>
  </dependency>
</dependencies>
```

== Gradle

Usage in Gradle

```groovy
dependencies {
  implementation platform("org.springframework.data:spring-data-bom:${calver.major.minor}")

  implementation("org.springframework.data:spring-data-commons")
}
```

== License

Spring Data Build is Open Source software released under the https://www.apache.org/licenses/LICENSE-2.0.html[Apache 2.0 license].
